pasarela:
  flyway:
    auto-repair: true

app:
  payments:
    mode: demo

logging:
  level:
    com.pasarela: DEBUG
    com.pasarela.application: DEBUG
    com.pasarela.infrastructure: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: INFO
